version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    healthcheck:
        test: pg_isready -U ${DB_USER} -d ${DB_NAME}
        interval: 3s
        timeout: 3s
        retries: 5

volumes:
  pg_data: